export const SET_IDENTITY = "SET_IDENTITY";
export const SET_ACTIVE_TEAM = "SET_ACTIVE_TEAM";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER";
export const SUBSCRIBED_TO_A_REMOTECI = "SUBSCRIBED_TO_A_REMOTECI";
export const UNSUBSCRIBED_FROM_A_REMOTECI = "UNSUBSCRIBED_FROM_A_REMOTECI";
